config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  match 'tasks/complete/:id' => 'tasks#complete', as: 'complete_task', via: :put

  resources :tasks


  root "tasks#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # root to: "home#index" 

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  # before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    # @tasks = Task.all
    @tasks = current_user.tasks
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    @task = Task.find(params[:id])
  end 

  def complete
    @task = current_user.tasks.find(params[:id])
    @task.completed = true
    @task.save
    redirect_to tasks_path
    # render index
   end
   

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to @task, notice: "Task was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end


  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      redirect_to @task
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task =Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # # Use callbacks to share common setup or constraints between actions.
    # def set_task
    #   @task = Task.find(params[:id])
    # end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :completed, :user_id)
      
      # params.fetch(:task, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

      <%= yield %>
      <p class="notice text-center"><%= notice %></p>
      <p class="alert text-center"><%= alert %></p>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="d-flex justify-content-center">
  <div class="text-center p-3 mb-2 bg-light text-dark w-45 ">
<%= form_with(model: task) do |form| %>
  <div class="field d-flex justify-content-between">
    <div class="p-2">
      <%= form.label :title %>
    </div>
    <%= form.text_field :title %>
    <% task.errors.full_messages_for(:title).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>
  <br>
  <div class="field d-flex justify-content-between">
    <div class="p-2">
      <%= form.label :description %>
    </div>
    <%= form.text_field :description %>
    <% task.errors.full_messages_for(:description).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>  
  <br>
  <%= form.hidden_field :completed, value: false %>
  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="form-group">
  <%= form.label :completed %>
  <%= form.check_box :completed %>
  </div>
    

  <div>
    <%= form.submit %>
  </div>
<% end %>
  </div>
</div>

app/views/tasks/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
     <%= link_to "Task Manager", tasks_path , class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-flex" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%= link_to "Home", tasks_path , class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Profile", edit_user_registration_path , class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "New Task", new_task_path , class: "nav-link"%>
        </li>
      </ul>
     <ul class="navbar-nav">
        <li class="nav-item">
          <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %> 
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <%= link_to task.title, task%>
  <p> <%=task.description%><p>
  <p> task.completed</p>
</div>

app/views/tasks/edit.html.erb
<%= render 'navbar'%>

<div class="d-flex justify-content-center">
  <h1>Editing task</h1>
  <hr>
  <br>
</div>
<%= render "form", task: @task %>

<br>

<div class="d-flex justify-content-center">
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<%# <p style="color: green"><%= notice %>
<%= render 'navbar' %>
<br>

<div class="d-flex justify-content-center">
  <div class="text-center p-4 mb-2 bg-light text-dark">
    <h1>Tasks</h1> 
    <p> Your have <%=@tasks.size%> tasks </p>
  </div>
</div>
<br>
<div class="row justify-content-center">
<table class="table table-striped table-hover table-bordered w-75">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th colspan="4" class="text-center">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
    <%# <% if !task.completed?%> 
      <tr>
        <td class="text-uppercase fst-italic text-center"><%= task.title %></td>
        <td class="fst-italic text-center"><%= task.description %></td>
        <td><%= task.completed ? 'Completed' : 'Pending' %></td>
        <td><%= link_to 'Completed', complete_task_path(task), data: {turbo_method: :put} ,class: 'btn btn-sm btn-success' %></td>
        <td><%= link_to 'Show', task, class: 'btn btn-sm btn-primary' %></td>
        <td><%= link_to 'Edit', edit_task_path(task), class: 'btn btn-sm btn-secondary' %></td>
        <td><%= link_to 'Destroy', task_path(task), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %></td>

      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/tasks/new.html.erb
<%= render 'tasks/navbar'%>
<br>
<div class="d-flex justify-content-center">
  <h1>New task</h1>
  <br>
</div>
<%= render "form", task: @task %>
<div class="d-flex justify-content-center">

<%= link_to "Back to tasks", tasks_path %>
<div>

app/views/tasks/show.html.erb
<%= render 'navbar'%>
<div class="container mt-5">
  <div class="row">
  <div class="col-md-6 offset-md-3">
  <div class="card">
    <div class="card-header text-center">
      <h2> <%=@task.title%> <h2> 
        <hr>
      <%if @task.completed %>
        <h4 class="text-success">Completed <h4>
      <% else %>
        <h4 class="text-danger"> Pending </h4> 
      <% end %>
    </div>
    <br>
    <div class="card-body text-center" >
      <h5> <%= @task.description%> <h5>

    </div>  

    <div class="d-flex card-footer gap-2 justify-content-center"">
      <%= link_to "Edit this task", edit_task_path(@task), class: "link-info" %> |
      <%= link_to "Back to tasks", tasks_path, class: "link-info" %>

    </div>
  </div>

  <br>
  <div class="d-flex justify-content-evenly">
    <%= link_to 'Completed', complete_task_path(@task), data: {turbo_method: :put} ,class: 'btn btn-success ' %> 
    <%= button_to "Destroy this task", @task, method: :delete, class: "btn btn-danger" %>
  </div>
  </div>
  </div>
</div>